# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5870db5e76559ed1d1f2279ff003005f904a5cece69b2962b124a579f26f570cea424db4620fb312e79b10b886aacb79ae09846f9b5744fe638230ab6f2c7d35

test:
  secret_key_base: 9c4b9dd7dda1bd43f4febbda3cfac988dfeadf792df7866380dfa193669df309f6db06d60008d745c67622b14b357cad7779d17e7c7f6c66b6bc8656565bdd7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
