# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dc7026a75885595a9b855b2f1a5156dc72f3e3d0dad74af74f512680d0d310f6b06b5f7aeb5241e2645800ee4e4dadcdfcbd402ad371f033d42005dfce4e801

test:
  secret_key_base: 3aed5b4709767128bde4618f075170b8180ac9a027703126ccd0dfc4355b20802c2aac0b4d7d41ba57e8090326bb4e048abda0545a99f78f9188ad22ab4db597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
